CREATE TABLE PLAYER(
	ID UUID NOT NULL,
	NAME VARCHAR(255) NOT NULL,
);

CREATE TABLE SESSION(
	ID UUID NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	CREATED_DATE BIGINT
);

CREATE TABLE ROLL(
	ID UUID NOT NULL,
	DIE_FACE NOT NULL INT,
	QUANTITY NOT NULL INT,
	BONUS_INCREMENT NOT NULL INT,
	PLAYER_ID NOT NULL BIGINT,
	SESSION_ID  NOT NULLBIGINT,
	SUM INT,
	ROLL_DATE NOT NULL BIGINT
);