CREATE TABLE player(
	ID UUID NOT NULL,
	NAME VARCHAR(255) NOT NULL
);

CREATE TABLE session(
	ID UUID NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL,
	PLAYERS VARCHAR(1024) NOT NULL,
	CREATED_DATE BIGINT
);

CREATE TABLE roll(
	ID UUID NOT NULL,
	DIE_FACE NOT NULL INT,
	QUANTITY NOT NULL INT,
	BONUS_INCREMENT NOT NULL INT,
	PLAYER_ID NOT NULL BIGINT,
	SESSION_ID NOT NULL BIGINT,
	SUM INT,
	ROLLED_DATE NOT NULL BIGINT,
	ROLLED_DICE VARCHAR(2048),
	MAX_VALUE BIGINT,
	MIN_VALUE BIGINT
);