CREATE TABLE PLAYER(
	ID INT AUTO_INCREMENT,
	NAME VARCHAR(255),
);

CREATE TABLE SESSION(
	ID INT AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255),
	PLAYERS VARCHAR(1024),
	CREATED_DATE BIGINT
);

CREATE TABLE ROLL(
	ID INT AUTO_INCREMENT,
	DIE_FACE INT,
	QUANTITY INT,
	BONUS_INCREMENT INT,
	PLAYER_ID BIGINT,
	SESSION_ID BIGINT,
	SUM INT,
	ROLLED_DATE BIGINT,
	ROLLED_DICE VARCHAR(2048),
	MAX_VALUE BIGINT,
	MIN_VALUE BIGINT
);

ALTER TABLE PLAYER ALTER NAME SET NOT NULL;